spring:
  datasource:
    url: jdbc:mysql://localhost:3306/olx-clients
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate :
        dialect: org.hibernate.dialect.MySQL8Dialect 
